apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: annuaire-preview
  namespace: argocd

spec:

  # Generator basé sur les Pull Requests GitHub.
  # PR ouverte = ArgoCD crée automatiquement une app de preview
  generators:
    - pullRequest:
        github:
          owner: laebernard
          repo: GitOps-avec-ArgoCD-
          tokenRef:
            secretName: github-token
            key: token
        requeueAfterSeconds: 60

  template:
    metadata:
      name: annuaire-preview-{{number}}
      labels:
        devhub.io/env: preview
        devhub.io/service: annuaire

    spec:
      project: devhub

      source:
        repoURL: https://github.com/laebernard/GitOps-avec-ArgoCD-.git
        targetRevision: '{{head_sha}}'
        path: services/annuaire/chart
        helm:
          valueFiles:
            - values-preview.yaml
          parameters:
            - name: ingress.host
              value: annuaire-pr-{{number}}.preview.devhub.local

      destination:
        server: https://kubernetes.default.svc
        namespace: devhub-preview-pr-{{number}}

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
