apiVersion: v999
kind: ConfigMap
metadata:
  name: {{ include "annuaire.fullname" . }}-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    {{- include "annuaire.labels" . | nindent 4 }}
data:
  APP_MESSAGE: "config loaded before deployment"
