apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "annuaire.fullname" . }}-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
  labels:
    {{- include "annuaire.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "annuaire.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: migration
          image: busybox:1.36
          command: ["sh", "-c", "echo migration ok"]
