# Application ArgoCD : annuaire-dev
#
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: annuaire-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: devhub

  source:
    repoURL: https://github.com/laebernard/GitOps-avec-ArgoCD-.git
    targetRevision: main
    path: services/annuaire/chart
    helm:
      valueFiles:
        - values-dev.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: devhub-dev

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    # Puis basculez en auto avec selfHeal:true / prune:false une fois validé.
    # automated:
    #   prune: false
    #   selfHeal: true